import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Evgeny Efimenko",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} bg-background text-foreground`}>
        <div className="mx-auto my-12 max-w-[692px] px-6 md:my-16">
          {children}
        </div>
      </body>
    </html>
  );
}
